name: 'Daily Job (Special)'

on:
  schedule:
    - cron: '30 23 * * *'  # UTC 时间每天 23:30 执行
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (for future use)'
        required: true
        default: 'production'

jobs:
  run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 升级到最新版本

      - name: Set up Python
        uses: actions/setup-python@v4  # 升级到最新版本
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 可选：安装项目依赖（如 requirements.txt）
          # pip install -r requirements.txt

      - name: Run Python script
        run: python assets/special/special.py

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add assets/special/special.txt
          # 仅在文件有变更时提交
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          else
            git commit -m ":tv: (special) AutoUpdate $(date -d '+8 hours' +'%Y%m%d')"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes
        if: steps.commit.outputs.changes == 'true'
        uses: ad-m/github-push-action@v0.6.0  # 使用固定版本号
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 可选：强制推送（谨慎使用）
          # force: true